"""Fetch/build the exact upstream WebRTC lock, without changing machine settings.

The optional media targets include the Windows host worker, native authorization
tests and release-guard checks. Real browser/input acceptance remains a separate
step. Default action verifies the source lock; fetching/building is explicit.
"""
from pathlib import Path
import argparse
import ast
import hashlib
import json
import os
import platform
import re
import shutil
import subprocess
import sys
import urllib.request

ROOT = Path(__file__).resolve().parents[1]
NATIVE = ROOT / "native/remote"


def run(command, cwd, env):
    # Never log process environment, which may contain authenticated proxy details.
    subprocess.run([str(item) for item in command], cwd=cwd, env=env, check=True)


def checkout(repository, revision, path, env, reviewed_difference=b""):
    path.mkdir(parents=True, exist_ok=True)
    if not (path / ".git").exists():
        run(["git", "init", "--quiet", path], ROOT, env)
        run(["git", "remote", "add", "origin", repository], path, env)
    origin = subprocess.check_output(["git", "remote", "get-url", "origin"], cwd=path, env=env, text=True).strip()
    if origin != repository:
        raise SystemExit("Refusing to reuse a checkout belonging to a different upstream")
    dirty = subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=no"], cwd=path, env=env, text=True)
    difference = subprocess.check_output(["git", "diff", "--binary"], cwd=path, env=env)
    if dirty and (not reviewed_difference or difference != reviewed_difference or subprocess.check_output(["git", "diff", "--cached", "--name-only"], cwd=path, env=env)):
        raise SystemExit("Refusing to overwrite modified dependency sources")
    run(["git", "-c", "core.longpaths=true", "fetch", "--depth=1", "origin", revision], path, env)
    run(["git", "-c", "core.longpaths=true", "checkout", "--detach", revision], path, env)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--fetch", action="store_true")
    parser.add_argument("--build", action="store_true")
    parser.add_argument("--build-existing", action="store_true", help="Build an already synced/hooked checkout after verifying its source identity")
    parser.add_argument("--windows-toolchain", type=Path, help="Portable toolchain manifest generated by prepare-remote-windows-sdk.py")
    parser.add_argument("--cache", type=Path, default=ROOT / ".downloads/remote-webrtc")
    parser.add_argument("--target-os", choices=["win", "linux", "mac", "android"])
    parser.add_argument("--target-cpu", choices=["x64", "arm64"], default="x64")
    parser.add_argument("--jobs", type=int, default=4, help="Maximum local compiler jobs")
    parser.add_argument("--media-probe", action="store_true", help="Also build the explicit local-only desktop media probe")
    parser.add_argument("--run-local-probe", action="store_true", help="Run an in-memory desktop loopback; no screen contents are saved")
    parser.add_argument("--probe-codec", choices=["VP8", "H264"], default="VP8", help="Force the local probe codec; H264 uses constrained baseline packetization-mode 1")
    args = parser.parse_args()
    if args.jobs < 1 or args.jobs > 64:
        parser.error("--jobs must be between 1 and 64")
    if args.run_local_probe and not args.media_probe:
        parser.error("--run-local-probe requires --media-probe")
    if args.media_probe and not (args.build or args.build_existing):
        parser.error("--media-probe requires --build or --build-existing")
    lock_bytes = (NATIVE / "remote-deps.lock.json").read_bytes()
    lock = json.loads(lock_bytes)
    version = re.search(r'const Version = "([^"]+)"', (ROOT / "internal/model/model.go").read_text(encoding="utf-8")).group(1)
    if f'HOST_VERSION = "{version}"' not in (NATIVE / "generated/host_version.hpp").read_text():
        raise SystemExit("Native host version differs from the client")
    for name, expected in [("DEPS", lock["webrtc"]["deps_sha256"]), ("WEBRTC-LICENSE", lock["webrtc"]["license_sha256"])]:
        if hashlib.sha256((NATIVE / "upstream" / name).read_bytes()).hexdigest() != expected:
            raise SystemExit("Checked-in upstream snapshot differs from the reviewed lock")
    for patch in lock["patches"]:
        if hashlib.sha256((NATIVE / patch["path"]).read_bytes()).hexdigest() != patch["sha256"]:
            raise SystemExit("Reviewed upstream patch differs from lock")
    if not args.fetch and not args.build and not args.build_existing:
        print("Remote dependency source lock verified; platform evidence is recorded separately in verified_builds")
        return
    env = os.environ.copy()
    for key in ("https", "http"):
        if key.upper() + "_PROXY" not in env and urllib.request.getproxies().get(key):
            env[key.upper() + "_PROXY"] = urllib.request.getproxies()[key]
    env.update({"DEPOT_TOOLS_UPDATE": "0", "DEPOT_TOOLS_WIN_TOOLCHAIN": "0", "PYTHONUTF8": "1"})
    cache = args.cache.resolve()
    depot = cache / "depot_tools"
    source = cache / "checkout/src"
    for spec, path in [(lock["depot_tools"], depot), (lock["webrtc"], source)]:
        source_patches = [patch for patch in lock["patches"] if patch["repository"] == "."] if path == source else []
        reviewed_difference = b"".join((NATIVE / patch["path"]).read_bytes() for patch in source_patches)
        if args.build_existing:
            revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=path, env=env, text=True).strip()
            dirty = subprocess.check_output(["git", "status", "--porcelain", "--untracked-files=no"], cwd=path, env=env, text=True)
            difference = subprocess.check_output(["git", "diff", "--binary"], cwd=path, env=env)
            staged = subprocess.check_output(["git", "diff", "--cached", "--name-only"], cwd=path, env=env)
            if revision != spec["revision"] or (dirty and (not reviewed_difference or difference != reviewed_difference or staged)):
                raise SystemExit("Existing checkout differs from the immutable source lock")
        else:
            checkout(spec["repository"], spec["revision"], path, env, reviewed_difference)
    # Hash the committed blob: Windows Git may check text out with CRLF.
    deps_blob = subprocess.check_output(["git", "show", "HEAD:DEPS"], cwd=source, env=env)
    if hashlib.sha256(deps_blob).hexdigest() != lock["webrtc"]["deps_sha256"]:
        raise SystemExit("Fetched WebRTC DEPS does not match lock")
    env["PATH"] = str(depot) + os.pathsep + env["PATH"]
    if os.name == "nt" and not (depot / "git.bat").exists():
        run(["cmd", "/d", "/c", depot / "bootstrap/win_tools.bat"], depot, env)
    target = args.target_os or {"Windows": "win", "Linux": "linux", "Darwin": "mac"}[platform.system()]
    if target == "android" and platform.system() != "Linux":
        raise SystemExit("The locked upstream Android build requires a Linux host")
    solution = {"name": "src", "url": lock["webrtc"]["repository"], "managed": False, "custom_deps": {}}
    config = "solutions = " + repr([solution]) + "\n"
    if target == "android":
        config += "target_os = ['android']\n"
    if not args.build_existing:
        (source.parent / ".gclient").write_text(config, encoding="utf-8")
        run([sys.executable, depot / "gclient.py", "sync", "--no-history", "--nohooks", "--revision", "src@" + lock["webrtc"]["revision"]], source.parent, env)
    if not args.build and not args.build_existing:
        print("Pinned WebRTC source and dependencies fetched; hooks/build were not run")
        return
    if not args.build_existing:
        run([sys.executable, depot / "gclient.py", "runhooks"], source.parent, env)
    clang_update = subprocess.check_output(["git", "show", "HEAD:clang/scripts/update.py"], cwd=source / "tools", env=env)
    if hashlib.sha256(clang_update).hexdigest() != lock["toolchain"]["clang_update_script_sha256"]:
        raise SystemExit("Fetched clang toolchain differs from lock")
    build_revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=source / "build", env=env, text=True).strip()
    if build_revision != lock["toolchain"]["chromium_build_revision"]:
        raise SystemExit("Fetched Chromium build tools differ from lock")
    for patch in lock["patches"]:
        patch_file = NATIVE / patch["path"]
        if hashlib.sha256(patch_file.read_bytes()).hexdigest() != patch["sha256"]:
            raise SystemExit("Reviewed upstream patch differs from lock")
        repository = source / patch["repository"]
        if subprocess.check_output(["git", "diff", "--cached", "--name-only"], cwd=repository, env=env):
            raise SystemExit("Refusing staged changes in a reviewed upstream patch repository")
        difference = subprocess.check_output(["git", "diff", "--binary"], cwd=repository, env=env)
        if not difference:
            run(["git", "apply", "--check", patch_file], repository, env)
            run(["git", "apply", patch_file], repository, env)
            difference = subprocess.check_output(["git", "diff", "--binary"], cwd=repository, env=env)
        if difference != patch_file.read_bytes():
            raise SystemExit("Upstream changes differ from the reviewed patch")
    build = source / "out/home_tunnel"
    build.mkdir(parents=True, exist_ok=True)
    gn_args = dict(lock["gn_args"], target_os=target, target_cpu=args.target_cpu)
    windows_toolchain_identity = None
    if target == "win":
        if args.windows_toolchain:
            manifest = json.loads(args.windows_toolchain.read_text())
            windows_toolchain_identity = {key: manifest[key] for key in ("visual_studio_version", "msvc_version", "windows_sdk_version", "sdk_package_sha256")}
            for key in ["visual_studio_path", "visual_studio_version", "windows_sdk_path", "windows_sdk_version", "wdk_path"]:
                gn_args[key] = manifest[key].replace("\\", "/")
            if manifest["windows_sdk_version"] != lock["toolchain"]["windows_sdk_version"]:
                raise SystemExit("Portable Windows SDK differs from upstream requirement")
            env["HT_RD_PORTABLE_WINDOWS_SDK"] = "1"
            env["HT_RD_STATIC_ENGINE_BUILD"] = "1"
            sdk = Path(manifest["windows_sdk_path"])
        else:
            sdk = Path(env.get("WINDOWSSDKDIR", r"C:\Program Files (x86)\Windows Kits\10"))
        required = sdk / "Include" / lock["toolchain"]["windows_sdk_version"] / "um/Windows.h"
        if not required.is_file():
            raise SystemExit("Locked WebRTC requires Windows SDK " + lock["toolchain"]["windows_sdk_version"] + "; use prepare-remote-windows-sdk.py for an isolated SDK")
    (build / "args.gn").write_text("\n".join(f"{name} = {json.dumps(value)}" for name, value in gn_args.items()) + "\n", encoding="utf-8")
    gn = source / "buildtools" / {"Windows": "win", "Linux": "linux64", "Darwin": "mac"}[platform.system()] / ("gn.exe" if os.name == "nt" else "gn")
    env["PATH"] = str(gn.parent) + os.pathsep + env["PATH"]
    gn_command = [gn, "gen", build]
    targets = ["webrtc"]
    if args.media_probe:
        overlay = source / "home_tunnel_remote"
        overlay.mkdir(exist_ok=True)
        for path in NATIVE.rglob("*"):
            if path.is_file():
                destination = overlay / path.relative_to(NATIVE)
                destination.parent.mkdir(parents=True, exist_ok=True)
                if not destination.is_file() or destination.read_bytes() != path.read_bytes():
                    shutil.copyfile(path, destination)
        gn_command += ["--root-target=//home_tunnel_remote/webrtc"]
        targets += ["home_tunnel_webrtc_probe", "home_tunnel_authorization_tests"]
        if target == "win":
            targets += ["home_tunnel_remote_host", "home_tunnel_input_guard_tests"]
    run(gn_command, source, env)
    print(f"Building with {args.jobs} jobs; compiler output: {build / 'remote-build.log'}", flush=True)
    with (build / "remote-build.log").open("w", encoding="utf-8") as log:
        result = subprocess.run([sys.executable, str(depot / "autoninja.py"), "-C", str(build), "-j", str(args.jobs), *targets], cwd=source, env=env, stdout=log, stderr=subprocess.STDOUT)
    if result.returncode:
        print("\n".join((build / "remote-build.log").read_text(encoding="utf-8", errors="replace").splitlines()[-80:]))
        raise SystemExit(result.returncode)
    artifact = build / "obj" / ("webrtc.lib" if target == "win" else "libwebrtc.a")
    if not artifact.is_file():
        raise SystemExit("Build did not produce the expected upstream static library")
    manifest = {"status": "upstream-engine-built-not-integrated", "webrtc_revision": lock["webrtc"]["revision"],
                "deps_lock_sha256": hashlib.sha256(lock_bytes).hexdigest(), "target_os": target,
                "target_cpu": args.target_cpu, "artifact_sha256": hashlib.sha256(artifact.read_bytes()).hexdigest(),
                "artifact_bytes": artifact.stat().st_size, "gn_args": gn_args}
    if args.media_probe:
        auth_tests = build / ("home_tunnel_authorization_tests.exe" if target == "win" else "home_tunnel_authorization_tests")
        run([auth_tests, NATIVE / "generated/remote-authorization-vectors.json"], build, env)
        if target == "win":
            run([build / "home_tunnel_input_guard_tests.exe"], build, env)
            host = build / "home_tunnel_remote_host.exe"
            revision = subprocess.check_output(["git", "rev-parse", "HEAD"], cwd=ROOT, text=True).strip()
            modified = bool(subprocess.check_output(["git", "status", "--porcelain"], cwd=ROOT, text=True).strip())
            host_manifest = {"schema_version": 1, "status": "built-acceptance-required", "executable": str(host),
                             "version": version, "repository_revision": revision, "source_modified": modified,
                             "target_os": target, "target_cpu": args.target_cpu,
                             "sha256": hashlib.sha256(host.read_bytes()).hexdigest(),
                             "webrtc_revision": lock["webrtc"]["revision"],
                             "deps_lock_sha256": hashlib.sha256(lock_bytes).hexdigest(),
                             "authorization_tests": "passed", "toolchain": lock["toolchain"]}
            host_manifest["actual_windows_toolchain"] = windows_toolchain_identity
            host_manifest["webrtc_source_patch_sha256"] = hashlib.sha256(subprocess.check_output(["git", "diff", "--binary"], cwd=source, env=env)).hexdigest()
            run([sys.executable, ROOT / "scripts/generate-remote-notices.py", "--source", source,
                 "--build", build, "--gn", gn], source, env)
            notices = build / "LICENSE.md"
            if not notices.is_file():
                raise SystemExit("Native dependency license bundle was not generated")
            host_manifest["notices_sha256"] = hashlib.sha256(notices.read_bytes()).hexdigest()
            # This is data written by gclient, not a Python module to execute.
            entries_ast = ast.parse((source.parent / ".gclient_entries").read_text(encoding="utf-8"))
            entries = ast.literal_eval(entries_ast.body[0].value)
            if not isinstance(entries, dict) or not all(isinstance(k, str) and isinstance(v, str) and v.startswith(("https://", "gs://")) for k, v in entries.items()):
                raise SystemExit("Unexpected dependency source manifest")
            entries["src"] = lock["webrtc"]["repository"] + "@" + lock["webrtc"]["revision"]
            sources = {"schema_version": 1, "repository": "ZHanry/home-tunnel-client", "revision": revision,
                       "worker_sha256": host_manifest["sha256"], "deps_lock": lock, "dependency_sources": entries,
                       "rebuild": "Check out the exact client revision and run scripts/build-native-windows.ps1. The source lock pins WebRTC, its DEPS, depot_tools, SDK packages and the reviewed upstream patch.",
                       "scope": "Corresponding source locations and build recipes; optional H.264/HEVC are not advertised as verified codecs."}
            sources_bytes = (json.dumps(sources, indent=2, sort_keys=True) + "\n").encode()
            (build / "remote-source-manifest.json").write_bytes(sources_bytes)
            host_manifest["source_manifest_sha256"] = hashlib.sha256(sources_bytes).hexdigest()
            (build / "remote-host-build.json").write_text(json.dumps(host_manifest, indent=2) + "\n", encoding="utf-8")
        probe = build / ("home_tunnel_webrtc_probe.exe" if target == "win" else "home_tunnel_webrtc_probe")
        manifest["probe_sha256"] = hashlib.sha256(probe.read_bytes()).hexdigest()
        if args.run_local_probe:
            result = subprocess.run([str(probe), "--local-desktop-loopback", "--codec=" + args.probe_codec], cwd=build, env=env, capture_output=True, text=True, timeout=90)
            evidence = json.loads(result.stdout) if result.stdout.strip() else {"status": "failed", "requested_codec": args.probe_codec}
            evidence["exit_code"] = result.returncode
            evidence["probe_sha256"] = manifest["probe_sha256"]
            evidence["webrtc_revision"] = lock["webrtc"]["revision"]
            evidence["deps_lock_sha256"] = hashlib.sha256(lock_bytes).hexdigest()
            (build / "remote-media-probe.json").write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
            (build / ("remote-media-probe-" + args.probe_codec.lower() + ".json")).write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
            manifest["local_probe"] = evidence
            if result.returncode:
                (build / "remote-webrtc-build.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
                # The probe emits bounded stage diagnostics only, never SDP/IPs.
                print(result.stderr[-4096:])
                print(json.dumps(evidence))
                raise SystemExit("Local native desktop media probe failed")
    (build / "remote-webrtc-build.json").write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print("Native artifacts and dependency sources recorded. Real browser/input and each advertised codec require separate acceptance.")


if __name__ == "__main__":
    main()
