// Home Tunnel Agent is a purpose-built FRP client for Home Tunnel.
//
// It intentionally exposes only the configuration surface generated by the
// Home Tunnel Windows client. It is not a general-purpose frpc command line.
package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"path/filepath"
	"regexp"
	"strings"
	"syscall"

	"github.com/fatedier/frp/client"
	"github.com/fatedier/frp/pkg/config"
	v1 "github.com/fatedier/frp/pkg/config/v1"
	"github.com/fatedier/frp/pkg/config/v1/validation"
	"github.com/fatedier/frp/pkg/util/log"
)

var (
	agentVersion = "0.0.0-dev"
	frpVersion   = "0.62.1"
	frpCommit    = "unknown"
)

const maxConfigBytes = 1024 * 1024

var (
	subdomainPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$`)
	domainPattern    = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$`)
)

type trustProfile struct {
	server string
	port   int
	domain string
}

func main() {
	if err := execute(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "Home Tunnel Agent:", err)
		os.Exit(1)
	}
}

func execute(args []string) error {
	if len(args) == 1 && (args[0] == "version" || args[0] == "--version") {
		fmt.Printf("Home Tunnel Agent %s (FRP %s, %s)\n", agentVersion, frpVersion, frpCommit)
		return nil
	}
	if len(args) == 0 || (args[0] != "verify" && args[0] != "run") {
		return errors.New("仅支持 version、verify 或 run 受管配置")
	}
	command := args[0]
	flags := flag.NewFlagSet(command, flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	var configPath, server, domain string
	var port int
	flags.StringVar(&configPath, "config", "", "managed configuration path")
	flags.StringVar(&server, "server", "", "user-selected FRPS host")
	flags.IntVar(&port, "port", 0, "user-selected FRPS port")
	flags.StringVar(&domain, "domain", "", "user-selected tunnel domain")
	if err := flags.Parse(args[1:]); err != nil || flags.NArg() != 0 {
		return errors.New("受管启动参数无效")
	}
	trust := trustProfile{
		server: strings.TrimSpace(server),
		port:   port,
		domain: strings.ToLower(strings.Trim(strings.TrimSpace(domain), ".")),
	}
	if err := validateTrustProfile(trust); err != nil {
		return err
	}

	common, proxies, err := loadManagedConfig(configPath, trust)
	if err != nil {
		return err
	}
	if command == "verify" {
		fmt.Printf("配置有效：%d 条受管连接\n", len(proxies))
		return nil
	}

	log.InitLogger(common.Log.To, common.Log.Level, int(common.Log.MaxDays), true)
	service, err := client.NewService(client.ServiceOptions{
		Common:         common,
		ProxyCfgs:      proxies,
		VisitorCfgs:    nil,
		ConfigFilePath: "",
	})
	if err != nil {
		return fmt.Errorf("初始化受管服务失败: %w", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if err := service.Run(ctx); err != nil {
		return fmt.Errorf("受管服务退出: %w", err)
	}
	return nil
}

func loadManagedConfig(path string, trust trustProfile) (*v1.ClientCommonConfig, []v1.ProxyConfigurer, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return nil, nil, fmt.Errorf("配置路径无效: %w", err)
	}
	if !strings.EqualFold(filepath.Ext(absolute), ".toml") {
		return nil, nil, errors.New("受管配置必须是 TOML 文件")
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return nil, nil, fmt.Errorf("无法读取受管配置: %w", err)
	}
	if !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxConfigBytes {
		return nil, nil, errors.New("受管配置大小或文件类型无效")
	}
	content, err := os.ReadFile(absolute)
	if err != nil {
		return nil, nil, fmt.Errorf("无法读取受管配置: %w", err)
	}
	if strings.Contains(string(content), "{{") || strings.Contains(string(content), "}}") {
		return nil, nil, errors.New("受管配置不允许模板表达式")
	}

	// FRP otherwise inherits http_proxy from the process. Home Tunnel connects
	// directly to the endpoint the user selected through the HTTPS control
	// center discovery flow and never delegates it to an ambient proxy variable.
	_ = os.Unsetenv("http_proxy")
	_ = os.Unsetenv("HTTP_PROXY")

	all := v1.ClientConfig{}
	if err := config.LoadConfigureFromFile(absolute, &all, true); err != nil {
		return nil, nil, fmt.Errorf("配置解析失败: %w", err)
	}
	common := &all.ClientCommonConfig
	common.Complete()
	proxies := make([]v1.ProxyConfigurer, 0, len(all.Proxies))
	for _, typed := range all.Proxies {
		typed.ProxyConfigurer.Complete(common.User)
		proxies = append(proxies, typed.ProxyConfigurer)
	}

	if warning, err := validation.ValidateAllClientConfig(common, proxies, nil); err != nil {
		return nil, nil, fmt.Errorf("配置校验失败: %w", err)
	} else if warning != nil {
		return nil, nil, fmt.Errorf("配置包含不受支持的兼容项: %v", warning)
	}
	if err := validateManagedSurface(common, all, proxies, trust); err != nil {
		return nil, nil, fmt.Errorf("配置超出 Home Tunnel 受管范围: %w", err)
	}
	return common, proxies, nil
}

func validateTrustProfile(trust trustProfile) error {
	if trust.server == "" || len(trust.server) > 253 || strings.ContainsAny(trust.server, "\r\n\t /\\") ||
		trust.port < 1 || trust.port > 65535 || !validTunnelDomain(trust.domain) {
		return errors.New("用户选择的服务器配置无效")
	}
	return nil
}

func validTunnelDomain(value string) bool {
	if len(value) > 253 || !domainPattern.MatchString(value) || !strings.Contains(value, ".") {
		return false
	}
	for _, label := range strings.Split(value, ".") {
		if !subdomainPattern.MatchString(label) {
			return false
		}
	}
	return true
}

func validateManagedSurface(common *v1.ClientCommonConfig, all v1.ClientConfig, proxies []v1.ProxyConfigurer, trust trustProfile) error {
	if !strings.EqualFold(common.ServerAddr, trust.server) || common.ServerPort != trust.port {
		return errors.New("配置与用户选择的服务器不一致")
	}
	if common.User == "" || len(common.User) > 128 || strings.ContainsAny(common.User, "\r\n\t ") {
		return errors.New("设备标识无效")
	}
	if common.Metadatas["home_tunnel_lease"] == "" || len(common.Metadatas) != 1 {
		return errors.New("安全租约元数据无效")
	}
	if len(all.Visitors) != 0 || len(common.IncludeConfigFiles) != 0 || len(common.Start) != 0 {
		return errors.New("不允许访客、外部配置或启动筛选")
	}
	if len(common.FeatureGates) != 0 || common.VirtualNet.Address != "" {
		return errors.New("不允许实验能力或虚拟网络")
	}
	if common.WebServer.Port != 0 || common.WebServer.User != "" || common.WebServer.Password != "" ||
		common.WebServer.AssetsDir != "" || common.WebServer.PprofEnable || common.WebServer.TLS != nil {
		return errors.New("不允许本地管理服务器")
	}
	if common.Auth.Method != v1.AuthMethodToken || common.Auth.Token != "" || len(common.Auth.AdditionalScopes) != 0 {
		return errors.New("认证配置无效")
	}
	if common.Transport.Protocol != "tcp" || common.Transport.ProxyURL != "" || common.Transport.ConnectServerLocalIP != "" {
		return errors.New("只允许直连 TCP 传输")
	}
	if common.Transport.HeartbeatInterval != 30 || common.Transport.HeartbeatTimeout != 90 {
		return errors.New("受管心跳配置无效")
	}
	if common.Transport.TLS.Enable == nil || !*common.Transport.TLS.Enable ||
		common.Transport.TLS.DisableCustomTLSFirstByte == nil || !*common.Transport.TLS.DisableCustomTLSFirstByte {
		return errors.New("必须启用受管 TLS")
	}
	if common.Transport.TLS.CertFile != "" || common.Transport.TLS.KeyFile != "" ||
		common.Transport.TLS.TrustedCaFile != "" || common.Transport.TLS.ServerName != "" {
		return errors.New("不允许自定义 TLS 文件")
	}
	if common.Log.To != "console" || common.Log.Level != "info" {
		return errors.New("日志配置无效")
	}
	if len(proxies) > 100 {
		return errors.New("连接数量超过上限")
	}
	for _, proxy := range proxies {
		if err := validateManagedProxy(proxy, trust.domain); err != nil {
			return err
		}
	}
	return nil
}

func validateManagedProxy(proxy v1.ProxyConfigurer, tunnelDomain string) error {
	httpProxy, ok := proxy.(*v1.HTTPProxyConfig)
	if !ok {
		return errors.New("只允许 HTTP 类型连接")
	}
	base := httpProxy.GetBaseConfig()
	if len(httpProxy.CustomDomains) != 1 || !isManagedDomain(httpProxy.CustomDomains[0], tunnelDomain) {
		return errors.New("公网域名不属于 Home Tunnel")
	}
	if len(httpProxy.Locations) != 0 || httpProxy.HTTPUser != "" || httpProxy.HTTPPassword != "" ||
		httpProxy.HostHeaderRewrite != "" || httpProxy.RouteByHTTPUser != "" ||
		len(httpProxy.RequestHeaders.Set) != 0 || len(httpProxy.ResponseHeaders.Set) != 0 {
		return errors.New("HTTP 高级选项不受支持")
	}
	if len(base.Annotations) != 0 || len(base.Metadatas) != 0 || base.LoadBalancer.Group != "" || base.LoadBalancer.GroupKey != "" {
		return errors.New("代理扩展选项不受支持")
	}
	if !base.Transport.UseEncryption || !base.Transport.UseCompression ||
		base.Transport.BandwidthLimit.String() != "0B" && base.Transport.BandwidthLimit.String() != "" ||
		base.Transport.ProxyProtocolVersion != "" {
		return errors.New("代理传输选项无效")
	}
	if base.HealthCheck.Type != "tcp" || base.HealthCheck.TimeoutSeconds != 3 || base.HealthCheck.IntervalSeconds != 10 {
		return errors.New("健康检查配置无效")
	}

	if base.Plugin.ClientPluginOptions == nil {
		if base.LocalPort < 1 || base.LocalPort > 65535 || !validLocalHost(base.LocalIP) {
			return errors.New("本地 HTTP 目标无效")
		}
		return nil
	}
	plugin, ok := base.Plugin.ClientPluginOptions.(*v1.HTTP2HTTPSPluginOptions)
	if !ok || base.Plugin.Type != v1.PluginHTTP2HTTPS || base.LocalPort != 0 {
		return errors.New("只允许受管 HTTPS 转换插件")
	}
	host, port, err := net.SplitHostPort(plugin.LocalAddr)
	if err != nil || !validLocalHost(host) || port == "0" {
		return errors.New("本地 HTTPS 目标无效")
	}
	if plugin.HostHeaderRewrite != host || len(plugin.RequestHeaders.Set) != 0 {
		return errors.New("HTTPS 主机设置无效")
	}
	return nil
}

func isManagedDomain(value string, tunnelDomain string) bool {
	domain := strings.ToLower(strings.TrimSpace(value))
	suffix := "." + strings.ToLower(strings.Trim(strings.TrimSpace(tunnelDomain), "."))
	if len(suffix) < 3 || !strings.HasSuffix(domain, suffix) {
		return false
	}
	return subdomainPattern.MatchString(strings.TrimSuffix(domain, suffix))
}

func validLocalHost(host string) bool {
	host = strings.TrimSpace(host)
	return host != "" && len(host) <= 253 && !strings.ContainsAny(host, "\r\n\t /\\")
}
