// Home Tunnel Agent is a purpose-built FRP client for Home Tunnel.
//
// It intentionally exposes only the configuration surface generated by the
// Home Tunnel Windows client. It is not a general-purpose frpc command line.
package main

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"flag"
	"fmt"
	"io"
	"net"
	"os"
	"os/signal"
	"path/filepath"
	"reflect"
	"regexp"
	"strings"
	"syscall"

	"github.com/fatedier/frp/client"
	"github.com/fatedier/frp/pkg/config"
	v1 "github.com/fatedier/frp/pkg/config/v1"
	"github.com/fatedier/frp/pkg/config/v1/validation"
	"github.com/fatedier/frp/pkg/util/log"
)

var (
	agentVersion = "0.0.0-dev"
	frpVersion   = "0.62.1"
	frpCommit    = "unknown"
)

const (
	maxConfigBytes = 1024 * 1024
	maxCaFileBytes = 64 * 1024
)

var (
	subdomainPattern = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?$`)
	domainPattern    = regexp.MustCompile(`^[a-z0-9](?:[a-z0-9.-]{0,251}[a-z0-9])?$`)
	sha256HexPattern = regexp.MustCompile(`^[0-9a-f]{64}$`)
)

type trustProfile struct {
	server string
	port   int
	domain string
	// tlsCaSha256 是客户端写入 frps-ca.pem 后计算的文件字节 SHA-256（小写
	// 十六进制）。为空表示服务端未下发 FRPS 证书，保持历史行为。
	tlsCaSha256 string
}

func main() {
	if err := execute(os.Args[1:]); err != nil {
		fmt.Fprintln(os.Stderr, "Home Tunnel Agent:", err)
		os.Exit(1)
	}
}

func execute(args []string) error {
	if len(args) == 1 && (args[0] == "version" || args[0] == "--version") {
		fmt.Printf("Home Tunnel Agent %s (FRP %s, %s)\n", agentVersion, frpVersion, frpCommit)
		return nil
	}
	if len(args) == 0 || (args[0] != "verify" && args[0] != "run") {
		return errors.New("仅支持 version、verify 或 run 受管配置")
	}
	command := args[0]
	flags := flag.NewFlagSet(command, flag.ContinueOnError)
	flags.SetOutput(io.Discard)
	var configPath, server, domain, tlsCaSha256 string
	var port int
	flags.StringVar(&configPath, "config", "", "managed configuration path")
	flags.StringVar(&server, "server", "", "user-selected FRPS host")
	flags.IntVar(&port, "port", 0, "user-selected FRPS port")
	flags.StringVar(&domain, "domain", "", "user-selected tunnel domain")
	flags.StringVar(&tlsCaSha256, "tls-ca-sha256", "", "expected SHA-256 of the managed FRPS CA file")
	if err := flags.Parse(args[1:]); err != nil || flags.NArg() != 0 {
		return errors.New("受管启动参数无效")
	}
	tlsCaSha256 = strings.ToLower(strings.TrimSpace(tlsCaSha256))
	if tlsCaSha256 != "" && !sha256HexPattern.MatchString(tlsCaSha256) {
		return errors.New("受管 CA 哈希参数无效")
	}
	trust := trustProfile{
		server:      strings.TrimSpace(server),
		port:        port,
		domain:      strings.ToLower(strings.Trim(strings.TrimSpace(domain), ".")),
		tlsCaSha256: tlsCaSha256,
	}
	if err := validateTrustProfile(trust); err != nil {
		return err
	}

	common, proxies, err := loadManagedConfig(configPath, trust)
	if err != nil {
		return err
	}
	if command == "verify" {
		fmt.Printf("配置有效：%d 条受管连接\n", len(proxies))
		return nil
	}

	log.InitLogger(common.Log.To, common.Log.Level, int(common.Log.MaxDays), true)
	service, err := client.NewService(client.ServiceOptions{
		Common:         common,
		ProxyCfgs:      proxies,
		VisitorCfgs:    nil,
		ConfigFilePath: "",
	})
	if err != nil {
		return fmt.Errorf("初始化受管服务失败: %w", err)
	}

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	if err := service.Run(ctx); err != nil {
		return fmt.Errorf("受管服务退出: %w", err)
	}
	return nil
}

func loadManagedConfig(path string, trust trustProfile) (*v1.ClientCommonConfig, []v1.ProxyConfigurer, error) {
	absolute, err := filepath.Abs(path)
	if err != nil {
		return nil, nil, fmt.Errorf("配置路径无效: %w", err)
	}
	if !strings.EqualFold(filepath.Ext(absolute), ".toml") {
		return nil, nil, errors.New("受管配置必须是 TOML 文件")
	}
	info, err := os.Stat(absolute)
	if err != nil {
		return nil, nil, fmt.Errorf("无法读取受管配置: %w", err)
	}
	if !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxConfigBytes {
		return nil, nil, errors.New("受管配置大小或文件类型无效")
	}
	content, err := os.ReadFile(absolute)
	if err != nil {
		return nil, nil, fmt.Errorf("无法读取受管配置: %w", err)
	}
	if strings.Contains(string(content), "{{") || strings.Contains(string(content), "}}") {
		return nil, nil, errors.New("受管配置不允许模板表达式")
	}

	// FRP otherwise inherits http_proxy from the process. Home Tunnel connects
	// directly to the endpoint the user selected through the HTTPS control
	// center discovery flow and never delegates it to an ambient proxy variable.
	_ = os.Unsetenv("http_proxy")
	_ = os.Unsetenv("HTTP_PROXY")

	all := v1.ClientConfig{}
	if err := config.LoadConfigureFromFile(absolute, &all, true); err != nil {
		return nil, nil, fmt.Errorf("配置解析失败: %w", err)
	}
	common := &all.ClientCommonConfig
	common.Complete()
	proxies := make([]v1.ProxyConfigurer, 0, len(all.Proxies))
	for _, typed := range all.Proxies {
		typed.ProxyConfigurer.Complete(common.User)
		proxies = append(proxies, typed.ProxyConfigurer)
	}

	if warning, err := validation.ValidateAllClientConfig(common, proxies, nil); err != nil {
		return nil, nil, fmt.Errorf("配置校验失败: %w", err)
	} else if warning != nil {
		return nil, nil, fmt.Errorf("配置包含不受支持的兼容项: %v", warning)
	}
	if err := validateManagedSurface(common, all, proxies, trust); err != nil {
		return nil, nil, fmt.Errorf("配置超出 Home Tunnel 受管范围: %w", err)
	}
	return common, proxies, nil
}

func validateTrustProfile(trust trustProfile) error {
	if trust.server == "" || len(trust.server) > 253 || strings.ContainsAny(trust.server, "\r\n\t /\\") ||
		trust.port < 1 || trust.port > 65535 || !validTunnelDomain(trust.domain) {
		return errors.New("用户选择的服务器配置无效")
	}
	return nil
}

func validTunnelDomain(value string) bool {
	if len(value) > 253 || !domainPattern.MatchString(value) || !strings.Contains(value, ".") {
		return false
	}
	for _, label := range strings.Split(value, ".") {
		if !subdomainPattern.MatchString(label) {
			return false
		}
	}
	return true
}

// validateManagedSurface 以白名单方式校验受管配置：先对少数合法可变字段做格式
// 校验并拷贝进按受管模板构造的期望配置，其余字段全部交给 FRP 的 Complete()
// 填充默认值，最后整体 DeepEqual。任何模板未声明的字段（包括 FRP 升级引入的
// 新字段）只要显式偏离默认值即被拒绝，默认拒绝而非黑名单枚举。
func validateManagedSurface(common *v1.ClientCommonConfig, all v1.ClientConfig, proxies []v1.ProxyConfigurer, trust trustProfile) error {
	// Visitors 不属于 ClientCommonConfig，DeepEqual 覆盖不到，单独禁止。
	if len(all.Visitors) != 0 {
		return errors.New("不允许访客配置")
	}
	// 前置校验保留语义化错误：服务器一致性、设备标识与租约元数据格式。
	if !strings.EqualFold(common.ServerAddr, trust.server) || common.ServerPort != trust.port {
		return errors.New("配置与用户选择的服务器不一致")
	}
	if common.User == "" || len(common.User) > 128 || strings.ContainsAny(common.User, "\r\n\t ") {
		return errors.New("设备标识无效")
	}
	if common.Metadatas["home_tunnel_lease"] == "" || len(common.Metadatas) != 1 {
		return errors.New("安全租约元数据无效")
	}

	// 受管模板固定字段：与两个客户端 RenderConfig 输出一一对应，
	// ServerAddr/ServerPort 直接取用户选择的 trust profile。
	expected := v1.ClientCommonConfig{
		ServerAddr:    trust.server,
		ServerPort:    trust.port,
		LoginFailExit: ptrTo(true),
		Auth:          v1.AuthClientConfig{Method: v1.AuthMethodToken},
		Transport: v1.ClientTransportConfig{
			Protocol:          "tcp",
			HeartbeatInterval: 30,
			HeartbeatTimeout:  90,
			TLS: v1.TLSClientConfig{
				Enable:                    ptrTo(true),
				DisableCustomTLSFirstByte: ptrTo(true),
			},
		},
		Log: v1.LogConfig{To: "console", Level: "info"},
	}
	// 合法可变字段：校验通过后拷贝进期望配置。
	expected.User = common.User
	expected.Metadatas = map[string]string{"home_tunnel_lease": common.Metadatas["home_tunnel_lease"]}
	if trust.tlsCaSha256 == "" {
		// 服务端未下发 FRPS 证书：保持历史行为，禁止一切自定义 TLS 文件。
		if common.Transport.TLS.TrustedCaFile != "" || common.Transport.TLS.ServerName != "" {
			return errors.New("不允许自定义 TLS 文件")
		}
	} else {
		// 客户端声明了受管 CA：配置必须固定到该 CA 文件与用户选择的服务器名，
		// 由 FRP 用它验证 FRPS 证书，防止租约令牌被中间人窃取。
		if common.Transport.TLS.TrustedCaFile == "" {
			return errors.New("缺少受管 FRPS CA 配置")
		}
		if err := validateTrustedCaFile(common.Transport.TLS.TrustedCaFile, trust.tlsCaSha256); err != nil {
			return err
		}
		if !strings.EqualFold(common.Transport.TLS.ServerName, trust.server) {
			return errors.New("TLS 服务器名称与用户选择的服务器不一致")
		}
		expected.Transport.TLS.TrustedCaFile = common.Transport.TLS.TrustedCaFile
		expected.Transport.TLS.ServerName = common.Transport.TLS.ServerName
	}
	// 由 FRP 填充全部默认值：未来新增字段若带非零默认值，两侧一致仍放行；
	// 配置显式写入任何偏离默认的值都会在 DeepEqual 处被拒。
	expected.Complete()
	// Complete 会把 http_proxy 环境变量写进 ProxyURL；受管模板固定直连，
	// 即使环境变量清理失败也绝不放行环境代理。
	expected.Transport.ProxyURL = ""
	if !reflect.DeepEqual(*common, expected) {
		return templateMismatchError("配置", *common, expected)
	}

	if len(proxies) > 100 {
		return errors.New("连接数量超过上限")
	}
	for _, proxy := range proxies {
		if err := validateManagedProxy(proxy, common.User, trust.domain); err != nil {
			return err
		}
	}
	return nil
}

// ptrTo 返回值的指针，用于构造模板中的 *bool 固定值。
func ptrTo[T any](value T) *T { return &value }

// templateMismatchError 生成默认拒绝错误，并尽力附上第一个偏离受管模板的
// 字段路径，方便定位手工构造配置里的问题字段。
func templateMismatchError(scope string, actual, expected any) error {
	if path := firstDiffPath("", reflect.ValueOf(actual), reflect.ValueOf(expected)); path != "" {
		return fmt.Errorf("%s超出受管模板：字段 %s 与模板不一致", scope, path)
	}
	return fmt.Errorf("%s超出受管模板", scope)
}

// firstDiffPath 深度优先遍历导出字段，返回实际值与期望值之间第一个不一致的
// 字段路径，找不到具体路径时返回空串。含未导出字段的类型（如带宽配额）不再
// 深入，在当前路径整体比较。仅用于生成诊断信息，判定始终以 DeepEqual 为准。
func firstDiffPath(path string, actual, expected reflect.Value) string {
	if actual.Type() != expected.Type() {
		return path
	}
	switch actual.Kind() {
	case reflect.Pointer, reflect.Interface:
		if actual.IsNil() != expected.IsNil() {
			return path
		}
		if actual.IsNil() {
			return ""
		}
		return firstDiffPath(path, actual.Elem(), expected.Elem())
	case reflect.Struct:
		for index := 0; index < actual.NumField(); index++ {
			field := actual.Type().Field(index)
			if !field.IsExported() {
				continue
			}
			childPath := field.Name
			if path != "" {
				childPath = path + "." + field.Name
			}
			if diff := firstDiffPath(childPath, actual.Field(index), expected.Field(index)); diff != "" {
				return diff
			}
		}
		if !reflect.DeepEqual(actual.Interface(), expected.Interface()) {
			return path
		}
		return ""
	default:
		if !reflect.DeepEqual(actual.Interface(), expected.Interface()) {
			return path
		}
		return ""
	}
}

// validateTrustedCaFile 确认配置引用的受管 CA 文件与客户端刚写入的内容完全一致，
// 防止手工构造的配置把信任锚替换成攻击者的证书。
func validateTrustedCaFile(path, expectedSha256 string) error {
	info, err := os.Stat(path)
	if err != nil {
		return fmt.Errorf("无法读取受管 CA 文件: %w", err)
	}
	if !info.Mode().IsRegular() || info.Size() <= 0 || info.Size() > maxCaFileBytes {
		return errors.New("受管 CA 文件大小或类型无效")
	}
	content, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("无法读取受管 CA 文件: %w", err)
	}
	digest := sha256.Sum256(content)
	if hex.EncodeToString(digest[:]) != expectedSha256 {
		return errors.New("受管 CA 文件哈希不一致")
	}
	return nil
}

// validateManagedProxy 对每条连接按白名单模板比对。可变输入只有 name、
// customDomains 里唯一的受管域名，以及本地后端：localIP+localPort（HTTP 直连）
// 或 http2https 插件的 localAddr+hostHeaderRewrite（HTTPS 后端）。校验可变项
// 格式后拷贝进期望配置，Complete 填充默认值，其余字段偏离模板即拒绝。
func validateManagedProxy(proxy v1.ProxyConfigurer, user, tunnelDomain string) error {
	httpProxy, ok := proxy.(*v1.HTTPProxyConfig)
	if !ok {
		return errors.New("只允许 HTTP 类型连接")
	}
	base := httpProxy.GetBaseConfig()
	if len(httpProxy.CustomDomains) != 1 || !isManagedDomain(httpProxy.CustomDomains[0], tunnelDomain) {
		return errors.New("公网域名不属于 Home Tunnel")
	}
	// subdomain 与 customDomains 并存时可绕过受管域名约束，保留明确错误。
	if httpProxy.SubDomain != "" {
		return errors.New("不允许 subdomain 配置")
	}
	expected := v1.HTTPProxyConfig{
		ProxyBaseConfig: v1.ProxyBaseConfig{
			Type:      "http",
			Transport: v1.ProxyTransport{UseEncryption: true, UseCompression: true},
			HealthCheck: v1.HealthCheckConfig{
				Type:            "tcp",
				TimeoutSeconds:  3,
				IntervalSeconds: 10,
			},
		},
		DomainConfig: v1.DomainConfig{CustomDomains: []string{httpProxy.CustomDomains[0]}},
	}
	if base.Plugin.ClientPluginOptions == nil {
		if base.LocalPort < 1 || base.LocalPort > 65535 || !validLocalHost(base.LocalIP) {
			return errors.New("本地 HTTP 目标无效")
		}
		expected.LocalIP = base.LocalIP
		expected.LocalPort = base.LocalPort
	} else {
		plugin, ok := base.Plugin.ClientPluginOptions.(*v1.HTTP2HTTPSPluginOptions)
		if !ok || base.Plugin.Type != v1.PluginHTTP2HTTPS {
			return errors.New("只允许受管 HTTPS 转换插件")
		}
		host, port, err := net.SplitHostPort(plugin.LocalAddr)
		if err != nil || !validLocalHost(host) || port == "0" {
			return errors.New("本地 HTTPS 目标无效")
		}
		if plugin.HostHeaderRewrite != host || len(plugin.RequestHeaders.Set) != 0 {
			return errors.New("HTTPS 主机设置无效")
		}
		expected.Plugin = v1.TypedClientPluginOptions{
			Type: v1.PluginHTTP2HTTPS,
			ClientPluginOptions: &v1.HTTP2HTTPSPluginOptions{
				Type:              v1.PluginHTTP2HTTPS,
				LocalAddr:         plugin.LocalAddr,
				HostHeaderRewrite: plugin.HostHeaderRewrite,
			},
		}
	}
	// Complete 填充默认值（含插件场景下 LocalIP 的 127.0.0.1 回填）并拼接
	// user 前缀；name 是客户端生成的可变项，实际值已含前缀，直接采用。
	expected.Complete(user)
	expected.Name = base.Name
	if !reflect.DeepEqual(httpProxy, &expected) {
		return templateMismatchError(fmt.Sprintf("连接 %q ", base.Name), *httpProxy, expected)
	}
	return nil
}

func isManagedDomain(value string, tunnelDomain string) bool {
	domain := strings.ToLower(strings.TrimSpace(value))
	suffix := "." + strings.ToLower(strings.Trim(strings.TrimSpace(tunnelDomain), "."))
	if len(suffix) < 3 || !strings.HasSuffix(domain, suffix) {
		return false
	}
	return subdomainPattern.MatchString(strings.TrimSuffix(domain, suffix))
}

func validLocalHost(host string) bool {
	host = strings.TrimSpace(host)
	return host != "" && len(host) <= 253 && !strings.ContainsAny(host, "\r\n\t /\\")
}
